---
- name: Установка Jenkins на Ubuntu
  hosts: jenkins-master
  become: true

  tasks:
    - name: Обновление списка пакетов
      apt:
        update_cache: yes

    - name: Установка зависимостей
      apt:
        name:
          - openjdk-8-jdk
          - wget
          - gnupg
          - software-properties-common
        state: present

    - name: Добавление ключа репозитория Jenkins
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key

    - name: Добавление репозитория Jenkins
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Установка Jenkins
      apt:
        name: jenkins
        state: present

    - name: Запуск службы Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes