---
all:
  hosts:
    jenkins-master:
      ansible_host: 158.160.64.230
    jenkins-agent:
      ansible_host: 158.160.81.89
  children:
    jenkins-master:
      hosts:
        jenkins-master:
    jenkins-agent:
      hosts:
        jenkins-agent:

  vars:
    ansible_connection_type: paramiko
    ansible_user: zodiak
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
