---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.68.57
    jenkins-agent-01:
      ansible_host: 84.201.162.127
    jenkins-agent-02:
      ansible_host: 158.160.75.12

  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
              jenkins-agent-02:
  vars:
    ansible_connection_type: paramiko
    ansible_user: zodiak
    ansible_ssh_private_key_file: ~/.ssh/id_rsa